TYPES = ["MUSIC", "VIDEO", "PODCAST"]

EARLY_REMINDER_DAY = 10

DURATION_MAP = {
    'FREE' : 1,
    'PERSONAL' : 1,
    'PREMIUM' : 3
}

TOPUP_DEVICE_RATES = {
    'FOUR_DEVICE':50,
    'TEN_DEVICE':100
}

SUBSCRIPTION_FEES = {
    'MUSIC' : {
        "FREE" : 0,
        "PERSONAL" : 100,
        "PREMIUM" : 250
        },
    
    'VIDEO' : {
        "FREE" : 0,
        "PERSONAL" : 200,
        "PREMIUM" : 500
        },
    
    'PODCAST' : {
        "FREE" : 0,
        "PERSONAL" : 100,
        "PREMIUM" : 300
        }
}

ERROR_CODES = {
    'ERR_DUPLICATE_TOPUP' : 'ADD_TOPUP_FAILED DUPLICATE_TOPUP',
    'ERR_ADD_TOPUP_INVALID_DATE' : 'ADD_TOPUP_FAILED INVALID_DATE',
    'ERR_INVALID_DATE' : 'INVALID_DATE',
    'ERR_ADD_SUBS_DUPLICATE_CATEGORY': 'ADD_SUBSCRIPTION_FAILED DUPLICATE_CATEGORY',
    'ERR_ADD_SUBS_INVALID_DATE' : 'ADD_SUBSCRIPTION_FAILED INVALID_DATE',
    'ERR_NO_SUBS' : 'SUBSCRIPTIONS_NOT_FOUND',
    'ERR_TOPUP_FOR_NO_SUBS' : 'ADD_TOPUP_FAILED SUBSCRIPTIONS_NOT_FOUND'
}